server:
  port: 8080
  servlet:
    context-path: /test
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#    username: root
#    password: 123456
#    type: com.mysql.cj.jdbc.MysqlDataSource

spring:
  profiles:
    active: dev

---

spring:
  profiles:
    default: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123456
    type: com.mysql.cj.jdbc.MysqlDataSource
    name: other
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:/mybatis/mapper/*.xml
  type-aliases-package: cn.ly.archive.study.test.domain

logging:
  level:
    cn.ly.common.datasource.mapper: debug